server:
  port: 7901
  tomcat:
    max-connections: 20000
    max-threads: 1000
    acceptCount: 1000
    min-spare-threads: 100
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    group: cn.jobonline.cloud.acm
    name: jobtbao-es-api
  profiles:
    active: local

alibaba:
  acm:
    group: jobonline
    file-extension: yml


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.jobtbao: DEBUG

#雪花算法初始值
snowflake:
  workerId: 1
  datacenterId: 1